### ISSUE TITLE
Main difference between channels and rooms?

### ISSUE THREAD

**Issue by devinivy** [cayasso/primus-multiplex#24]
Does someone mind clarifying exactly what the difference is between channels and rooms?  I recognize that there is a difference, but I'd like to understand the relationship between them and their particular uses.  Would you ever use both in tandem?  Any idea if primus-rooms and primus-multiplex play well together?

**Comment by lpinca** [comment]
Hi,
sorry for the delay.
`primus-rooms` offers a way to group different connections into a logical space (a room).
`primus-multiplex` allows you to define multiple communication channels over a single connection.
I can't think of a use case where it makes sense to use both in tandem at the moment.
As far as I know, they work fine together.

**Comment by devinivy** [comment]
Perfect!  Thanks for the explanation.
