### ISSUE TITLE
Spark disconnect

### ISSUE THREAD

**Issue by mathieumg** [cayasso/primus-multiplex#25]
When doing `spark.end()` in the `connection` event for a channel, as demonstrated in https://github.com/cayasso/primus-multiplex#sparkendfn, is it supposed to terminate the Primus connection like it would on a vanilla Primus spark? If so, for me it doesn't. However, if I add `this.conn.end()` after this line https://github.com/cayasso/primus-multiplex/blob/d9367e00814268c6ebb679697b6cda6285b32669/lib/server/spark.js#L152 it does work properly. Is this by design, or an oversight?

Until then, or if that's by design, I imagine I can do `spark.conn.end()` instead. 

Thank you!

**Comment by lpinca** [comment]
I think this has been done on purpose. Calling `end` on a subconnection should only close that subconnection. If you close the main connection all subconnections are closed.

For example on a single client you may have multiple subconnections:
```js
var a = primus.channel('news');
var b = primus.channel('news');
var c = primus.channel('news');
```
The current implementation ensures that `spark.end()` closes only one of these.

**Comment by mathieumg** [comment]
Alright, as long as I can voluntarily kill the whole connection with `spark.end.conn`, that's fine by me. Thanks!

**Comment by lpinca** [comment]
@mathieumg not sure if you have to do it from the channel, but you can also call `end` on the `spark` object that comes from primus.

```
primus.on('connection', (spark) => {
  spark.end();
});
```

that would have the same effect.

**Comment by mathieumg** [comment]
Yeah I'm aware, but in my case the disconnection has to occur because of something that happened within the channel's context. Thanks, however. :smile:
